import { Image } from '../model/image';

export const IMAGES: Image[] = [
  {
    name: 'ISIC_0024306.jpg',
    metaClinicalAge_approx: 45,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024307.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024308.jpg',
    metaClinicalAge_approx: 55,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024309.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024310.jpg',
    metaClinicalAge_approx: 60,
    metaClinicalAnatom_site_general: 'anterior torso',
    metaClinicalBenign_malignant: 'malignant',
    meta01X: '1',
    metaClinicalDiagnosis: 'melanoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024311.jpg',
    metaClinicalAge_approx: 75,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024312.jpg',
    metaClinicalAge_approx: 75,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'pigmented benign keratosis',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024313.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'malignant',
    meta01X: '1',
    metaClinicalDiagnosis: 'melanoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024314.jpg',
    metaClinicalAge_approx: 75,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024315.jpg',
    metaClinicalAge_approx: 55,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'malignant',
    meta01X: '1',
    metaClinicalDiagnosis: 'melanoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024316.jpg',
    metaClinicalAge_approx: 55,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024317.jpg',
    metaClinicalAge_approx: 35,
    metaClinicalAnatom_site_general: 'anterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024318.jpg',
    metaClinicalAge_approx: 65,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'dermatofibroma',
    metaClinicalDiagnosis_confirm_type: 'single image expert consensus',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024319.jpg',
    metaClinicalAge_approx: 55,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024320.jpg',
    metaClinicalAge_approx: 65,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024321.jpg',
    metaClinicalAge_approx: 35,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024322.jpg',
    metaClinicalAge_approx: 65,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024323.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'malignant',
    meta01X: '1',
    metaClinicalDiagnosis: 'melanoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  /*
  {
    name: 'ISIC_0024324.jpg',
    metaClinicalAge_approx: 85,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'pigmented benign keratosis',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024325.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024326.jpg',
    metaClinicalAge_approx: 75,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024327.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024328.jpg',
    metaClinicalAge_approx: 55,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024329.jpg',
    metaClinicalAge_approx: 75,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'actinic keratosis',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024330.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'dermatofibroma',
    metaClinicalDiagnosis_confirm_type: 'single image expert consensus',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024331.jpg',
    metaClinicalAge_approx: 65,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'basal cell carcinoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024332.jpg',
    metaClinicalAge_approx: 60,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'basal cell carcinoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024333.jpg',
    metaClinicalAge_approx: 85,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'malignant',
    meta01X: '1',
    metaClinicalDiagnosis: 'melanoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024334.jpg',
    metaClinicalAge_approx: 45,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024335.jpg',
    metaClinicalAge_approx: 45,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024336.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'pigmented benign keratosis',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024337.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'pigmented benign keratosis',
    metaClinicalDiagnosis_confirm_type: 'single image expert consensus',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024338.jpg',
    metaClinicalAge_approx: 45,
    metaClinicalAnatom_site_general: 'head/neck',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'pigmented benign keratosis',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024339.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024340.jpg',
    metaClinicalAge_approx: 10,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024341.jpg',
    metaClinicalAge_approx: 25,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024342.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024343.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024344.jpg',
    metaClinicalAge_approx: 85,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024345.jpg',
    metaClinicalAge_approx: 85,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'basal cell carcinoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024346.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024347.jpg',
    metaClinicalAge_approx: 25,
    metaClinicalAnatom_site_general: 'upper extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024348.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024349.jpg',
    metaClinicalAge_approx: 35,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024350.jpg',
    metaClinicalAge_approx: 35,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024351.jpg',
    metaClinicalAge_approx: 70,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'malignant',
    meta01X: '1',
    metaClinicalDiagnosis: 'melanoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024352.jpg',
    metaClinicalAge_approx: 30,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024353.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024354.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: 'anterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024355.jpg',
    metaClinicalAge_approx: 35,
    metaClinicalAnatom_site_general: 'upper extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024356.jpg',
    metaClinicalAge_approx: 75,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024357.jpg',
    metaClinicalAge_approx: 45,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024358.jpg',
    metaClinicalAge_approx: 60,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'pigmented benign keratosis',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024359.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024360.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'anterior torso',
    metaClinicalBenign_malignant: null,
    meta01X: 'x',
    metaClinicalDiagnosis: 'basal cell carcinoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024361.jpg',
    metaClinicalAge_approx: 35,
    metaClinicalAnatom_site_general: 'anterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024362.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024363.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024364.jpg',
    metaClinicalAge_approx: 45,
    metaClinicalAnatom_site_general: 'upper extremity',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: 'ISIC_0024365.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'anterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024366.jpg',
    metaClinicalAge_approx: 35,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024367.jpg',
    metaClinicalAge_approx: 35,
    metaClinicalAnatom_site_general: 'posterior torso',
    metaClinicalBenign_malignant: 'malignant',
    meta01X: '1',
    metaClinicalDiagnosis: 'melanoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'female'
  },
  {
    name: 'ISIC_0024368.jpg',
    metaClinicalAge_approx: 65,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  },
  {
    name: '.jpg',
    metaClinicalAge_approx: 65,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    meta01X: '0',
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalMelanocytic: false,
    metaClinicalSex: 'male'
  } */
];
