import { Image } from '../model/image';

export const IMAGES: Image[] = [
  {
    id: '5aaf12491165976913627e89',
    name: 'ISIC_0024306.jpg',
    metaClinicalAge_approx: 45,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    metaClinicalClin_size_long_diam_mm: null,
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalFamily_hx_mm: null,
    metaClinicalMel_class: null,
    metaClinicalMel_mitotic_index: null,
    metaClinicalMel_thick_mm: null,
    metaClinicalMel_type: null,
    metaClinicalMel_ulcer: null,
    metaClinicalMelanocytic: false,
    metaClinicalNevus_type: null,
    metaClinicalPersonal_hx_mm: null,
    metaClinicalSex: 'male',
    metaAcquisitionDermoscopic_type: null,
    metaAcquisitionImage_type: 'dermoscopic',
    metaAcquisitionPixelsX: 600,
    metaAcquisitionPixelsY: 450
  },
  {
    id: '5aaf12491165976913627e95',
    name: 'ISIC_0024307.jpg',
    metaClinicalAge_approx: 50,
    metaClinicalAnatom_site_general: 'lower extremity',
    metaClinicalBenign_malignant: 'benign',
    metaClinicalClin_size_long_diam_mm: null,
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalFamily_hx_mm: null,
    metaClinicalMel_class: null,
    metaClinicalMel_mitotic_index: null,
    metaClinicalMel_thick_mm: null,
    metaClinicalMel_type: null,
    metaClinicalMel_ulcer: null,
    metaClinicalMelanocytic: false,
    metaClinicalNevus_type: null,
    metaClinicalPersonal_hx_mm: null,
    metaClinicalSex: 'male',
    metaAcquisitionDermoscopic_type: null,
    metaAcquisitionImage_type: 'dermoscopic',
    metaAcquisitionPixelsX: 600,
    metaAcquisitionPixelsY: 450
  },
  {
    id: '5aaf12491165976913627ea0',
    name: 'ISIC_0024308.jpg',
    metaClinicalAge_approx: 55,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    metaClinicalClin_size_long_diam_mm: null,
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalFamily_hx_mm: null,
    metaClinicalMel_class: null,
    metaClinicalMel_mitotic_index: null,
    metaClinicalMel_thick_mm: null,
    metaClinicalMel_type: null,
    metaClinicalMel_ulcer: null,
    metaClinicalMelanocytic: false,
    metaClinicalNevus_type: null,
    metaClinicalPersonal_hx_mm: null,
    metaClinicalSex: 'female',
    metaAcquisitionDermoscopic_type: null,
    metaAcquisitionImage_type: 'dermoscopic',
    metaAcquisitionPixelsX: 600,
    metaAcquisitionPixelsY: 450
  },
  {
    id: '5aaf12491165976913627eab',
    name: 'ISIC_0024309.jpg',
    metaClinicalAge_approx: 40,
    metaClinicalAnatom_site_general: null,
    metaClinicalBenign_malignant: 'benign',
    metaClinicalClin_size_long_diam_mm: null,
    metaClinicalDiagnosis: 'nevus',
    metaClinicalDiagnosis_confirm_type: 'serial imaging showing no change',
    metaClinicalFamily_hx_mm: null,
    metaClinicalMel_class: null,
    metaClinicalMel_mitotic_index: null,
    metaClinicalMel_thick_mm: null,
    metaClinicalMel_type: null,
    metaClinicalMel_ulcer: null,
    metaClinicalMelanocytic: false,
    metaClinicalNevus_type: null,
    metaClinicalPersonal_hx_mm: null,
    metaClinicalSex: 'male',
    metaAcquisitionDermoscopic_type: null,
    metaAcquisitionImage_type: 'dermoscopic',
    metaAcquisitionPixelsX: 600,
    metaAcquisitionPixelsY: 450
  },
  {
    id: '5aaf12491165976913627eb6',
    name: 'ISIC_0024310.jpg',
    metaClinicalAge_approx: 60,
    metaClinicalAnatom_site_general: 'anterior torso',
    metaClinicalBenign_malignant: 'malignant',
    metaClinicalClin_size_long_diam_mm: null,
    metaClinicalDiagnosis: 'melanoma',
    metaClinicalDiagnosis_confirm_type: 'histopathology',
    metaClinicalFamily_hx_mm: null,
    metaClinicalMel_class: null,
    metaClinicalMel_mitotic_index: null,
    metaClinicalMel_thick_mm: null,
    metaClinicalMel_type: null,
    metaClinicalMel_ulcer: null,
    metaClinicalMelanocytic: false,
    metaClinicalNevus_type: null,
    metaClinicalPersonal_hx_mm: null,
    metaClinicalSex: 'male',
    metaAcquisitionDermoscopic_type: null,
    metaAcquisitionImage_type: 'dermoscopic',
    metaAcquisitionPixelsX: 600,
    metaAcquisitionPixelsY: 450
  }
];
